services:
  - type: web
    name: kshop-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: kshop-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: bookmakerp@gmail.com
      - key: EMAIL_PASS
        value: ton_mot_de_passe_app